language: node_js

node_js:
- 'node'

branches:
  only:
    - main

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9"
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      sleep 3
    fi

install:
  - npm install

script:
  - npm run tslint
  - npm run compile
  - npm run build-plugin
